name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Specify the operating system

    steps:
    - uses: actions/checkout@v2  # Check out the repository
    - name: Set up Python  # Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies  # Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script  # Run your Python script
      run: python script.py
